---
name: "PostgreSQL Database"
guid: "27e7ad18-ea71-4b19-b1a9-6e4c2e4d5e18"
version: "1.0.0.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "PostgreSQL database provider for Jellyfin"
description: >
  Adds PostgreSQL database support to Jellyfin server. Configure using
  standard PostgreSQL environment variables (POSTGRES_HOST, POSTGRES_PORT,
  POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD).
category: "General"
owner: "jellyfin"
artifacts:
- "Jellyfin.Plugin.Pgsql.dll"
changelog: >
  Initial PostgreSQL database provider implementation
